=== kyra28/AdvancedMail/services/XML/src/xsd/discussion.xsd
<?xml version="1.0"?>

<xs:schema 	xmlns:xs="http://www.w3.org/2001/XMLSchema"
			elementFormDefault="qualified">

	<xs:include schemaLocation="dis2.xsd"/>
	
 	<xs:element name="echange">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="mail" type="mailType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
    </xs:element>   
	
	<xs:complexType name="mailType">
		<xs:sequence>
			<xs:element name="header" type="headerType"/>
			<xs:element name="body" type="bodyType" minOccurs="0"/>
			<xs:element ref="reponses"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="reponseAttendueType">
		<xs:choice>
			<xs:element name="libre" type="emptyType"/>
			<xs:element name="num" type="emptyType"/>
			<xs:element name="date" type="emptyType"/>
			<xs:element name="tel" type="emptyType"/>
			<xs:element name="choix" type="valuesType"/>
			<xs:element name="selecteur" type="valuesType"/>
		</xs:choice>
	</xs:complexType>
	
	
	<xs:complexType name="emptyType"/>
	
	<xs:complexType name="valuesType">
		<xs:sequence>
			<xs:element name="value" type="xs:string" minOccurs="2" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="blockType">
		<xs:sequence>
			<xs:element name="text" type="xs:string"/>
			<xs:element name="reponseAttendue" type="reponseAttendueType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="bodyType">
		<xs:sequence>
			<xs:element name="block" type="blockType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="headerType">
		<xs:sequence>
			<xs:element name="expediteur" type="xs:string"/>
			<xs:element name="destinataire" type="xs:string"/>
			<xs:element name="objet" type="xs:string"/>
			<xs:element name="date" type="xs:dateTime"/>
			<xs:element name="xsdFileName" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="libreType">
		<xs:sequence>
			<xs:element name="question" type="xs:string"/>
			<xs:element name="valeur" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="numType">
		<xs:sequence>
			<xs:element name="question" type="xs:string"/>
			<xs:element name="valeur" type="xs:decimal" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="dateType">
		<xs:sequence>
			<xs:element name="question" type="xs:string"/>
			<xs:element name="valeur" type="xs:date" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="telType">
		<xs:sequence>
			<xs:element name="question" type="xs:string"/>
			<xs:element name="valeur" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="choixType">
		<xs:sequence>
			<xs:element name="question" type="xs:string"/>
			<xs:element name="valeur" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="selecteurType">
		<xs:sequence>
			<xs:element name="question" type="xs:string"/>
			<xs:element name="valeur" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	
</xs:schema>

=== kyra28/AdvancedMail/services/XML/src/main/resources/com/polytech/xml/services/echange.xml
<?xml version="1.0" encoding="UTF-8"?>

<echange 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="discussion.xsd">
	<mail>
		<header>
			<expediteur></expediteur>
			<destinataire>ANtoine</destinataire>
			<objet></objet>
			<date>2002-05-30T09:00:00</date>
		</header>
		<body>
			<block>
				<text>Comment tu vas</text>
				<reponseAttendue>
					<libre/>
				</reponseAttendue>
			</block>
		</body>
		<reponses/>
	</mail>
	
</echange>
